services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - SERVER_HOSTNAMES=${SERVER_HOSTNAMES}
    ports:
      - 5070:5070
      - 8989:8989
      - 9117:9117
      - 8080:8080
      - 7878:7878

    volumes:
      - ./config/vpn:/gluetun
    restart: unless-stopped

  portainer_agent:
    image: portainer/agent:2.33.1
    container_name: portainer_agent
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host

  ubuntu-wget:
    image: ubuntu:latest
    container_name: ubuntu-wget
    tty: true
    stdin_open: true
    command: /bin/bash -c "apt update && apt install wget -y && watch -n 1 wget -qO- ifconfig.me/ip"
    network_mode: "service:vpn"
    depends_on:
      - vpn
    #apt update && apt install wget -y && watch -n 1 wget -qO- ifconfig.me/ip
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./data/radarr:/config
      - ./data/movies:/movies
      - ./data/downloads:/downloads
    network_mode: "service:vpn"
    depends_on:
      - vpn
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./data/sonarr:/config
      - ./data/tv:/tv
      - ./data/downloads:/downloads
    network_mode: "service:vpn"
    depends_on:
      - vpn
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./data/jackett:/config
    network_mode: "service:vpn"
    depends_on:
      - vpn
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${WEBUI_PORT}
    volumes:
      - ./data/qbittorrent:/config
      - ./data/downloads:/downloads
    # ports:
    #   - 6881:6881
    #   - 6881:6881/udp
    network_mode: "service:vpn"
    depends_on:
      - vpn
    restart: unless-stopped